/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetDashboardQueryResult,
} from '../models/index';
import {
    GetDashboardQueryResultFromJSON,
    GetDashboardQueryResultToJSON,
} from '../models/index';

export interface ApiDashboardGetRequest {
    year?: number;
    month?: number;
}

/**
 * 
 */
export class DashboardApi extends runtime.BaseAPI {

    /**
     */
    async apiDashboardGetRaw(requestParameters: ApiDashboardGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDashboardQueryResult>> {
        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Dashboard`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDashboardQueryResultFromJSON(jsonValue));
    }

    /**
     */
    async apiDashboardGet(requestParameters: ApiDashboardGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDashboardQueryResult> {
        const response = await this.apiDashboardGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
