/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMonthlyTransactionCommand,
  MonthlyTransaction,
  ProblemDetails,
  UpdateMonthlyTransactionCommand,
} from '../models/index';
import {
    CreateMonthlyTransactionCommandFromJSON,
    CreateMonthlyTransactionCommandToJSON,
    MonthlyTransactionFromJSON,
    MonthlyTransactionToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UpdateMonthlyTransactionCommandFromJSON,
    UpdateMonthlyTransactionCommandToJSON,
} from '../models/index';

export interface ApiMonthlyTransactionsIdDeleteRequest {
    id: string;
}

export interface ApiMonthlyTransactionsIdGetRequest {
    id: string;
}

export interface ApiMonthlyTransactionsIdPutRequest {
    id: string;
    updateMonthlyTransactionCommand?: UpdateMonthlyTransactionCommand;
}

export interface ApiMonthlyTransactionsPostRequest {
    createMonthlyTransactionCommand?: CreateMonthlyTransactionCommand;
}

/**
 * 
 */
export class MonthlyTransactionsApi extends runtime.BaseAPI {

    /**
     */
    async apiMonthlyTransactionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MonthlyTransaction>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/monthly-transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MonthlyTransactionFromJSON));
    }

    /**
     */
    async apiMonthlyTransactionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MonthlyTransaction>> {
        const response = await this.apiMonthlyTransactionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMonthlyTransactionsIdDeleteRaw(requestParameters: ApiMonthlyTransactionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMonthlyTransactionsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/monthly-transactions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMonthlyTransactionsIdDelete(requestParameters: ApiMonthlyTransactionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMonthlyTransactionsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMonthlyTransactionsIdGetRaw(requestParameters: ApiMonthlyTransactionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonthlyTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMonthlyTransactionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/monthly-transactions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonthlyTransactionFromJSON(jsonValue));
    }

    /**
     */
    async apiMonthlyTransactionsIdGet(requestParameters: ApiMonthlyTransactionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonthlyTransaction> {
        const response = await this.apiMonthlyTransactionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMonthlyTransactionsIdPutRaw(requestParameters: ApiMonthlyTransactionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonthlyTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMonthlyTransactionsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/monthly-transactions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMonthlyTransactionCommandToJSON(requestParameters['updateMonthlyTransactionCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonthlyTransactionFromJSON(jsonValue));
    }

    /**
     */
    async apiMonthlyTransactionsIdPut(requestParameters: ApiMonthlyTransactionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonthlyTransaction> {
        const response = await this.apiMonthlyTransactionsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMonthlyTransactionsPostRaw(requestParameters: ApiMonthlyTransactionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonthlyTransaction>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/monthly-transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMonthlyTransactionCommandToJSON(requestParameters['createMonthlyTransactionCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonthlyTransactionFromJSON(jsonValue));
    }

    /**
     */
    async apiMonthlyTransactionsPost(requestParameters: ApiMonthlyTransactionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonthlyTransaction> {
        const response = await this.apiMonthlyTransactionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
