/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePlannedExpenseCommand,
  PlannedExpense,
  ProblemDetails,
  UpdatePlannedExpenseCommand,
} from '../models/index';
import {
    CreatePlannedExpenseCommandFromJSON,
    CreatePlannedExpenseCommandToJSON,
    PlannedExpenseFromJSON,
    PlannedExpenseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UpdatePlannedExpenseCommandFromJSON,
    UpdatePlannedExpenseCommandToJSON,
} from '../models/index';

export interface ApiPlannedExpensesIdDeleteRequest {
    id: string;
}

export interface ApiPlannedExpensesIdGetRequest {
    id: string;
}

export interface ApiPlannedExpensesIdPutRequest {
    id: string;
    updatePlannedExpenseCommand?: UpdatePlannedExpenseCommand;
}

export interface ApiPlannedExpensesPostRequest {
    createPlannedExpenseCommand?: CreatePlannedExpenseCommand;
}

/**
 * 
 */
export class PlannedExpensesApi extends runtime.BaseAPI {

    /**
     */
    async apiPlannedExpensesIdDeleteRaw(requestParameters: ApiPlannedExpensesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlannedExpensesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/PlannedExpenses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPlannedExpensesIdDelete(requestParameters: ApiPlannedExpensesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPlannedExpensesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPlannedExpensesIdGetRaw(requestParameters: ApiPlannedExpensesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlannedExpense>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlannedExpensesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/PlannedExpenses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlannedExpenseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlannedExpensesIdGet(requestParameters: ApiPlannedExpensesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlannedExpense> {
        const response = await this.apiPlannedExpensesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlannedExpensesIdPutRaw(requestParameters: ApiPlannedExpensesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlannedExpense>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlannedExpensesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/PlannedExpenses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePlannedExpenseCommandToJSON(requestParameters['updatePlannedExpenseCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlannedExpenseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlannedExpensesIdPut(requestParameters: ApiPlannedExpensesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlannedExpense> {
        const response = await this.apiPlannedExpensesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlannedExpensesPostRaw(requestParameters: ApiPlannedExpensesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlannedExpense>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/PlannedExpenses`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePlannedExpenseCommandToJSON(requestParameters['createPlannedExpenseCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlannedExpenseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlannedExpensesPost(requestParameters: ApiPlannedExpensesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlannedExpense> {
        const response = await this.apiPlannedExpensesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
