/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSavingCommand,
  ProblemDetails,
  Saving,
  UpdateSavingCommand,
} from '../models/index';
import {
    CreateSavingCommandFromJSON,
    CreateSavingCommandToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SavingFromJSON,
    SavingToJSON,
    UpdateSavingCommandFromJSON,
    UpdateSavingCommandToJSON,
} from '../models/index';

export interface ApiSavingsIdDeleteRequest {
    id: string;
}

export interface ApiSavingsIdGetRequest {
    id: string;
}

export interface ApiSavingsIdPutRequest {
    id: string;
    updateSavingCommand?: UpdateSavingCommand;
}

export interface ApiSavingsPostRequest {
    createSavingCommand?: CreateSavingCommand;
}

/**
 * 
 */
export class SavingsApi extends runtime.BaseAPI {

    /**
     */
    async apiSavingsIdDeleteRaw(requestParameters: ApiSavingsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSavingsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Savings/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiSavingsIdDelete(requestParameters: ApiSavingsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiSavingsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiSavingsIdGetRaw(requestParameters: ApiSavingsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Saving>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSavingsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Savings/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavingFromJSON(jsonValue));
    }

    /**
     */
    async apiSavingsIdGet(requestParameters: ApiSavingsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Saving> {
        const response = await this.apiSavingsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSavingsIdPutRaw(requestParameters: ApiSavingsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Saving>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSavingsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Savings/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSavingCommandToJSON(requestParameters['updateSavingCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavingFromJSON(jsonValue));
    }

    /**
     */
    async apiSavingsIdPut(requestParameters: ApiSavingsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Saving> {
        const response = await this.apiSavingsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSavingsPostRaw(requestParameters: ApiSavingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Saving>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Savings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSavingCommandToJSON(requestParameters['createSavingCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavingFromJSON(jsonValue));
    }

    /**
     */
    async apiSavingsPost(requestParameters: ApiSavingsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Saving> {
        const response = await this.apiSavingsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
