/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountType
 */
export interface AccountType {
    /**
     * 
     * @type {string}
     * @memberof AccountType
     */
    name?: string | null;
}

/**
 * Check if a given object implements the AccountType interface.
 */
export function instanceOfAccountType(value: object): value is AccountType {
    return true;
}

export function AccountTypeFromJSON(json: any): AccountType {
    return AccountTypeFromJSONTyped(json, false);
}

export function AccountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountType {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AccountTypeToJSON(json: any): AccountType {
    return AccountTypeToJSONTyped(json, false);
}

export function AccountTypeToJSONTyped(value?: AccountType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

