/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 * 
 * @export
 * @interface AccountDashboardGroupDto
 */
export interface AccountDashboardGroupDto {
    /**
     * 
     * @type {string}
     * @memberof AccountDashboardGroupDto
     */
    groupName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AccountDashboardGroupDto
     */
    total?: number;
    /**
     * 
     * @type {Array<Account>}
     * @memberof AccountDashboardGroupDto
     */
    accounts?: Array<Account> | null;
}

/**
 * Check if a given object implements the AccountDashboardGroupDto interface.
 */
export function instanceOfAccountDashboardGroupDto(value: object): value is AccountDashboardGroupDto {
    return true;
}

export function AccountDashboardGroupDtoFromJSON(json: any): AccountDashboardGroupDto {
    return AccountDashboardGroupDtoFromJSONTyped(json, false);
}

export function AccountDashboardGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDashboardGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupName': json['groupName'] == null ? undefined : json['groupName'],
        'total': json['total'] == null ? undefined : json['total'],
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(AccountFromJSON)),
    };
}

export function AccountDashboardGroupDtoToJSON(json: any): AccountDashboardGroupDto {
    return AccountDashboardGroupDtoToJSONTyped(json, false);
}

export function AccountDashboardGroupDtoToJSONTyped(value?: AccountDashboardGroupDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupName': value['groupName'],
        'total': value['total'],
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(AccountToJSON)),
    };
}

