/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    currentBalance?: number;
    /**
     * 
     * @type {AccountType}
     * @memberof Account
     */
    accountType?: AccountType;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    isArchived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    image?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    updatedAt?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Account
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    type?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    sumsToMonthlyBudget?: boolean;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'currentBalance': json['currentBalance'] == null ? undefined : json['currentBalance'],
        'accountType': json['accountType'] == null ? undefined : AccountTypeFromJSON(json['accountType']),
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'color': json['color'] == null ? undefined : json['color'],
        'image': json['image'] == null ? undefined : json['image'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'type': json['type'] == null ? undefined : json['type'],
        'sumsToMonthlyBudget': json['sumsToMonthlyBudget'] == null ? undefined : json['sumsToMonthlyBudget'],
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'name': value['name'],
        'currentBalance': value['currentBalance'],
        'accountType': AccountTypeToJSON(value['accountType']),
        'isArchived': value['isArchived'],
        'color': value['color'],
        'image': value['image'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'metadata': value['metadata'],
        'type': value['type'],
        'sumsToMonthlyBudget': value['sumsToMonthlyBudget'],
    };
}

