/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 * 
 * @export
 * @interface AccountPagedResult
 */
export interface AccountPagedResult {
    /**
     * 
     * @type {number}
     * @memberof AccountPagedResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountPagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountPagedResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountPagedResult
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AccountPagedResult
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccountPagedResult
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {Array<Account>}
     * @memberof AccountPagedResult
     */
    data?: Array<Account> | null;
}

/**
 * Check if a given object implements the AccountPagedResult interface.
 */
export function instanceOfAccountPagedResult(value: object): value is AccountPagedResult {
    return true;
}

export function AccountPagedResultFromJSON(json: any): AccountPagedResult {
    return AccountPagedResultFromJSONTyped(json, false);
}

export function AccountPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountPagedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AccountFromJSON)),
    };
}

export function AccountPagedResultToJSON(json: any): AccountPagedResult {
    return AccountPagedResultToJSONTyped(json, false);
}

export function AccountPagedResultToJSONTyped(value?: AccountPagedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccountToJSON)),
    };
}

