/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetSectionItemDto } from './BudgetSectionItemDto';
import {
    BudgetSectionItemDtoFromJSON,
    BudgetSectionItemDtoFromJSONTyped,
    BudgetSectionItemDtoToJSON,
    BudgetSectionItemDtoToJSONTyped,
} from './BudgetSectionItemDto';

/**
 * 
 * @export
 * @interface BudgetSectionDto
 */
export interface BudgetSectionDto {
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionDto
     */
    total?: number;
    /**
     * 
     * @type {Array<BudgetSectionItemDto>}
     * @memberof BudgetSectionDto
     */
    items?: Array<BudgetSectionItemDto> | null;
}

/**
 * Check if a given object implements the BudgetSectionDto interface.
 */
export function instanceOfBudgetSectionDto(value: object): value is BudgetSectionDto {
    return true;
}

export function BudgetSectionDtoFromJSON(json: any): BudgetSectionDto {
    return BudgetSectionDtoFromJSONTyped(json, false);
}

export function BudgetSectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetSectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(BudgetSectionItemDtoFromJSON)),
    };
}

export function BudgetSectionDtoToJSON(json: any): BudgetSectionDto {
    return BudgetSectionDtoToJSONTyped(json, false);
}

export function BudgetSectionDtoToJSONTyped(value?: BudgetSectionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(BudgetSectionItemDtoToJSON)),
    };
}

