/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyTransactionType } from './MonthlyTransactionType';
import {
    MonthlyTransactionTypeFromJSON,
    MonthlyTransactionTypeFromJSONTyped,
    MonthlyTransactionTypeToJSON,
    MonthlyTransactionTypeToJSONTyped,
} from './MonthlyTransactionType';

/**
 * 
 * @export
 * @interface BudgetSectionItemDto
 */
export interface BudgetSectionItemDto {
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    userId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionItemDto
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BudgetSectionItemDto
     */
    isApplied?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionItemDto
     */
    dayOfMonth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    name?: string | null;
    /**
     * 
     * @type {MonthlyTransactionType}
     * @memberof BudgetSectionItemDto
     */
    monthlyTransactionType?: MonthlyTransactionType;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    accountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    subcategory?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionItemDto
     */
    goalAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionItemDto
     */
    savedAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetSectionItemDto
     */
    amountPerMonth?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BudgetSectionItemDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BudgetSectionItemDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof BudgetSectionItemDto
     */
    type?: string | null;
}



/**
 * Check if a given object implements the BudgetSectionItemDto interface.
 */
export function instanceOfBudgetSectionItemDto(value: object): value is BudgetSectionItemDto {
    return true;
}

export function BudgetSectionItemDtoFromJSON(json: any): BudgetSectionItemDto {
    return BudgetSectionItemDtoFromJSONTyped(json, false);
}

export function BudgetSectionItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetSectionItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'isApplied': json['isApplied'] == null ? undefined : json['isApplied'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
        'name': json['name'] == null ? undefined : json['name'],
        'monthlyTransactionType': json['monthlyTransactionType'] == null ? undefined : MonthlyTransactionTypeFromJSON(json['monthlyTransactionType']),
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'goalAmount': json['goalAmount'] == null ? undefined : json['goalAmount'],
        'savedAmount': json['savedAmount'] == null ? undefined : json['savedAmount'],
        'amountPerMonth': json['amountPerMonth'] == null ? undefined : json['amountPerMonth'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function BudgetSectionItemDtoToJSON(json: any): BudgetSectionItemDto {
    return BudgetSectionItemDtoToJSONTyped(json, false);
}

export function BudgetSectionItemDtoToJSONTyped(value?: BudgetSectionItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'amount': value['amount'],
        'isApplied': value['isApplied'],
        'notes': value['notes'],
        'dayOfMonth': value['dayOfMonth'],
        'icon': value['icon'],
        'color': value['color'],
        'name': value['name'],
        'monthlyTransactionType': MonthlyTransactionTypeToJSON(value['monthlyTransactionType']),
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'subcategory': value['subcategory'],
        'goalAmount': value['goalAmount'],
        'savedAmount': value['savedAmount'],
        'amountPerMonth': value['amountPerMonth'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'type': value['type'],
    };
}

