/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayActivitySummary } from './DayActivitySummary';
import {
    DayActivitySummaryFromJSON,
    DayActivitySummaryFromJSONTyped,
    DayActivitySummaryToJSON,
    DayActivitySummaryToJSONTyped,
} from './DayActivitySummary';

/**
 * 
 * @export
 * @interface CalendarView
 */
export interface CalendarView {
    /**
     * 
     * @type {string}
     * @memberof CalendarView
     */
    yearMonth?: string | null;
    /**
     * 
     * @type {Array<DayActivitySummary>}
     * @memberof CalendarView
     */
    days?: Array<DayActivitySummary> | null;
}

/**
 * Check if a given object implements the CalendarView interface.
 */
export function instanceOfCalendarView(value: object): value is CalendarView {
    return true;
}

export function CalendarViewFromJSON(json: any): CalendarView {
    return CalendarViewFromJSONTyped(json, false);
}

export function CalendarViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarView {
    if (json == null) {
        return json;
    }
    return {
        
        'yearMonth': json['yearMonth'] == null ? undefined : json['yearMonth'],
        'days': json['days'] == null ? undefined : ((json['days'] as Array<any>).map(DayActivitySummaryFromJSON)),
    };
}

export function CalendarViewToJSON(json: any): CalendarView {
    return CalendarViewToJSONTyped(json, false);
}

export function CalendarViewToJSONTyped(value?: CalendarView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'yearMonth': value['yearMonth'],
        'days': value['days'] == null ? undefined : ((value['days'] as Array<any>).map(DayActivitySummaryToJSON)),
    };
}

