/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CategoryType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type CategoryType = typeof CategoryType[keyof typeof CategoryType];


export function instanceOfCategoryType(value: any): boolean {
    for (const key in CategoryType) {
        if (Object.prototype.hasOwnProperty.call(CategoryType, key)) {
            if (CategoryType[key as keyof typeof CategoryType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryTypeFromJSON(json: any): CategoryType {
    return CategoryTypeFromJSONTyped(json, false);
}

export function CategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryType {
    return json as CategoryType;
}

export function CategoryTypeToJSON(value?: CategoryType | null): any {
    return value as any;
}

export function CategoryTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CategoryType {
    return value as CategoryType;
}

