/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePlannedExpenseCommand
 */
export interface CreatePlannedExpenseCommand {
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreatePlannedExpenseCommand
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePlannedExpenseCommand
     */
    isRecurring?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreatePlannedExpenseCommand
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    categoryImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    categoryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedExpenseCommand
     */
    subCategory?: string | null;
}

/**
 * Check if a given object implements the CreatePlannedExpenseCommand interface.
 */
export function instanceOfCreatePlannedExpenseCommand(value: object): value is CreatePlannedExpenseCommand {
    return true;
}

export function CreatePlannedExpenseCommandFromJSON(json: any): CreatePlannedExpenseCommand {
    return CreatePlannedExpenseCommandFromJSONTyped(json, false);
}

export function CreatePlannedExpenseCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlannedExpenseCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'isRecurring': json['isRecurring'] == null ? undefined : json['isRecurring'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryImage': json['categoryImage'] == null ? undefined : json['categoryImage'],
        'categoryColor': json['categoryColor'] == null ? undefined : json['categoryColor'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
    };
}

export function CreatePlannedExpenseCommandToJSON(json: any): CreatePlannedExpenseCommand {
    return CreatePlannedExpenseCommandToJSONTyped(json, false);
}

export function CreatePlannedExpenseCommandToJSONTyped(value?: CreatePlannedExpenseCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'isRecurring': value['isRecurring'],
        'totalAmount': value['totalAmount'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryImage': value['categoryImage'],
        'categoryColor': value['categoryColor'],
        'subCategory': value['subCategory'],
    };
}

