/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSavingCommand
 */
export interface CreateSavingCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateSavingCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSavingCommand
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSavingCommand
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateSavingCommand
     */
    goalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSavingCommand
     */
    savedAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSavingCommand
     */
    amountPerMonth?: number;
}

/**
 * Check if a given object implements the CreateSavingCommand interface.
 */
export function instanceOfCreateSavingCommand(value: object): value is CreateSavingCommand {
    return true;
}

export function CreateSavingCommandFromJSON(json: any): CreateSavingCommand {
    return CreateSavingCommandFromJSONTyped(json, false);
}

export function CreateSavingCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSavingCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
        'goalAmount': json['goalAmount'] == null ? undefined : json['goalAmount'],
        'savedAmount': json['savedAmount'] == null ? undefined : json['savedAmount'],
        'amountPerMonth': json['amountPerMonth'] == null ? undefined : json['amountPerMonth'],
    };
}

export function CreateSavingCommandToJSON(json: any): CreateSavingCommand {
    return CreateSavingCommandToJSONTyped(json, false);
}

export function CreateSavingCommandToJSONTyped(value?: CreateSavingCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'icon': value['icon'],
        'color': value['color'],
        'goalAmount': value['goalAmount'],
        'savedAmount': value['savedAmount'],
        'amountPerMonth': value['amountPerMonth'],
    };
}

