/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyTransactionType } from './MonthlyTransactionType';
import {
    MonthlyTransactionTypeFromJSON,
    MonthlyTransactionTypeFromJSONTyped,
    MonthlyTransactionTypeToJSON,
    MonthlyTransactionTypeToJSONTyped,
} from './MonthlyTransactionType';

/**
 * 
 * @export
 * @interface CreateMonthlyTransactionCommand
 */
export interface CreateMonthlyTransactionCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateMonthlyTransactionCommand
     */
    amount?: number;
    /**
     * 
     * @type {MonthlyTransactionType}
     * @memberof CreateMonthlyTransactionCommand
     */
    monthlyTransactionType?: MonthlyTransactionType;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateMonthlyTransactionCommand
     */
    dayOfMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    accountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMonthlyTransactionCommand
     */
    subcategory?: string | null;
}



/**
 * Check if a given object implements the CreateMonthlyTransactionCommand interface.
 */
export function instanceOfCreateMonthlyTransactionCommand(value: object): value is CreateMonthlyTransactionCommand {
    return true;
}

export function CreateMonthlyTransactionCommandFromJSON(json: any): CreateMonthlyTransactionCommand {
    return CreateMonthlyTransactionCommandFromJSONTyped(json, false);
}

export function CreateMonthlyTransactionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonthlyTransactionCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'monthlyTransactionType': json['monthlyTransactionType'] == null ? undefined : MonthlyTransactionTypeFromJSON(json['monthlyTransactionType']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
    };
}

export function CreateMonthlyTransactionCommandToJSON(json: any): CreateMonthlyTransactionCommand {
    return CreateMonthlyTransactionCommandToJSONTyped(json, false);
}

export function CreateMonthlyTransactionCommandToJSONTyped(value?: CreateMonthlyTransactionCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'monthlyTransactionType': MonthlyTransactionTypeToJSON(value['monthlyTransactionType']),
        'notes': value['notes'],
        'dayOfMonth': value['dayOfMonth'],
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'subcategory': value['subcategory'],
    };
}

