/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardBalance
 */
export interface DashboardBalance {
    /**
     * 
     * @type {number}
     * @memberof DashboardBalance
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardBalance
     */
    accountCount?: number;
}

/**
 * Check if a given object implements the DashboardBalance interface.
 */
export function instanceOfDashboardBalance(value: object): value is DashboardBalance {
    return true;
}

export function DashboardBalanceFromJSON(json: any): DashboardBalance {
    return DashboardBalanceFromJSONTyped(json, false);
}

export function DashboardBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'accountCount': json['accountCount'] == null ? undefined : json['accountCount'],
    };
}

export function DashboardBalanceToJSON(json: any): DashboardBalance {
    return DashboardBalanceToJSONTyped(json, false);
}

export function DashboardBalanceToJSONTyped(value?: DashboardBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'accountCount': value['accountCount'],
    };
}

