/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayActivitySummary
 */
export interface DayActivitySummary {
    /**
     * 
     * @type {Date}
     * @memberof DayActivitySummary
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof DayActivitySummary
     */
    hasExpenses?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DayActivitySummary
     */
    hasNotAppliedExpenses?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DayActivitySummary
     */
    hasIncome?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DayActivitySummary
     */
    hasNotAppliedIncome?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DayActivitySummary
     */
    hasTransfers?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DayActivitySummary
     */
    expenseCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DayActivitySummary
     */
    notAppliedExpenseCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DayActivitySummary
     */
    incomeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DayActivitySummary
     */
    notAppliedIncomeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DayActivitySummary
     */
    transferCount?: number;
}

/**
 * Check if a given object implements the DayActivitySummary interface.
 */
export function instanceOfDayActivitySummary(value: object): value is DayActivitySummary {
    return true;
}

export function DayActivitySummaryFromJSON(json: any): DayActivitySummary {
    return DayActivitySummaryFromJSONTyped(json, false);
}

export function DayActivitySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayActivitySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'hasExpenses': json['hasExpenses'] == null ? undefined : json['hasExpenses'],
        'hasNotAppliedExpenses': json['hasNotAppliedExpenses'] == null ? undefined : json['hasNotAppliedExpenses'],
        'hasIncome': json['hasIncome'] == null ? undefined : json['hasIncome'],
        'hasNotAppliedIncome': json['hasNotAppliedIncome'] == null ? undefined : json['hasNotAppliedIncome'],
        'hasTransfers': json['hasTransfers'] == null ? undefined : json['hasTransfers'],
        'expenseCount': json['expenseCount'] == null ? undefined : json['expenseCount'],
        'notAppliedExpenseCount': json['notAppliedExpenseCount'] == null ? undefined : json['notAppliedExpenseCount'],
        'incomeCount': json['incomeCount'] == null ? undefined : json['incomeCount'],
        'notAppliedIncomeCount': json['notAppliedIncomeCount'] == null ? undefined : json['notAppliedIncomeCount'],
        'transferCount': json['transferCount'] == null ? undefined : json['transferCount'],
    };
}

export function DayActivitySummaryToJSON(json: any): DayActivitySummary {
    return DayActivitySummaryToJSONTyped(json, false);
}

export function DayActivitySummaryToJSONTyped(value?: DayActivitySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'hasExpenses': value['hasExpenses'],
        'hasNotAppliedExpenses': value['hasNotAppliedExpenses'],
        'hasIncome': value['hasIncome'],
        'hasNotAppliedIncome': value['hasNotAppliedIncome'],
        'hasTransfers': value['hasTransfers'],
        'expenseCount': value['expenseCount'],
        'notAppliedExpenseCount': value['notAppliedExpenseCount'],
        'incomeCount': value['incomeCount'],
        'notAppliedIncomeCount': value['notAppliedIncomeCount'],
        'transferCount': value['transferCount'],
    };
}

