/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarView } from './CalendarView';
import {
    CalendarViewFromJSON,
    CalendarViewFromJSONTyped,
    CalendarViewToJSON,
    CalendarViewToJSONTyped,
} from './CalendarView';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';
import type { DashboardBalance } from './DashboardBalance';
import {
    DashboardBalanceFromJSON,
    DashboardBalanceFromJSONTyped,
    DashboardBalanceToJSON,
    DashboardBalanceToJSONTyped,
} from './DashboardBalance';

/**
 * 
 * @export
 * @interface GetDashboardQueryResult
 */
export interface GetDashboardQueryResult {
    /**
     * 
     * @type {DashboardBalance}
     * @memberof GetDashboardQueryResult
     */
    balance?: DashboardBalance;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof GetDashboardQueryResult
     */
    recentTransactions?: Array<Transaction> | null;
    /**
     * 
     * @type {CalendarView}
     * @memberof GetDashboardQueryResult
     */
    calendarView?: CalendarView;
}

/**
 * Check if a given object implements the GetDashboardQueryResult interface.
 */
export function instanceOfGetDashboardQueryResult(value: object): value is GetDashboardQueryResult {
    return true;
}

export function GetDashboardQueryResultFromJSON(json: any): GetDashboardQueryResult {
    return GetDashboardQueryResultFromJSONTyped(json, false);
}

export function GetDashboardQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDashboardQueryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : DashboardBalanceFromJSON(json['balance']),
        'recentTransactions': json['recentTransactions'] == null ? undefined : ((json['recentTransactions'] as Array<any>).map(TransactionFromJSON)),
        'calendarView': json['calendarView'] == null ? undefined : CalendarViewFromJSON(json['calendarView']),
    };
}

export function GetDashboardQueryResultToJSON(json: any): GetDashboardQueryResult {
    return GetDashboardQueryResultToJSONTyped(json, false);
}

export function GetDashboardQueryResultToJSONTyped(value?: GetDashboardQueryResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': DashboardBalanceToJSON(value['balance']),
        'recentTransactions': value['recentTransactions'] == null ? undefined : ((value['recentTransactions'] as Array<any>).map(TransactionToJSON)),
        'calendarView': CalendarViewToJSON(value['calendarView']),
    };
}

