/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * 
 * @export
 * @interface GetTransactionsByMonthQueryResult
 */
export interface GetTransactionsByMonthQueryResult {
    /**
     * 
     * @type {string}
     * @memberof GetTransactionsByMonthQueryResult
     */
    yearMonth?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetTransactionsByMonthQueryResult
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransactionsByMonthQueryResult
     */
    totalExpenses?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransactionsByMonthQueryResult
     */
    totalIncome?: number;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof GetTransactionsByMonthQueryResult
     */
    transactions?: Array<Transaction> | null;
}

/**
 * Check if a given object implements the GetTransactionsByMonthQueryResult interface.
 */
export function instanceOfGetTransactionsByMonthQueryResult(value: object): value is GetTransactionsByMonthQueryResult {
    return true;
}

export function GetTransactionsByMonthQueryResultFromJSON(json: any): GetTransactionsByMonthQueryResult {
    return GetTransactionsByMonthQueryResultFromJSONTyped(json, false);
}

export function GetTransactionsByMonthQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionsByMonthQueryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'yearMonth': json['yearMonth'] == null ? undefined : json['yearMonth'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
        'totalIncome': json['totalIncome'] == null ? undefined : json['totalIncome'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function GetTransactionsByMonthQueryResultToJSON(json: any): GetTransactionsByMonthQueryResult {
    return GetTransactionsByMonthQueryResultToJSONTyped(json, false);
}

export function GetTransactionsByMonthQueryResultToJSONTyped(value?: GetTransactionsByMonthQueryResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'yearMonth': value['yearMonth'],
        'totalCount': value['totalCount'],
        'totalExpenses': value['totalExpenses'],
        'totalIncome': value['totalIncome'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(TransactionToJSON)),
    };
}

