/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncomesAfterMonthlyExpensesData } from './IncomesAfterMonthlyExpensesData';
import {
    IncomesAfterMonthlyExpensesDataFromJSON,
    IncomesAfterMonthlyExpensesDataFromJSONTyped,
    IncomesAfterMonthlyExpensesDataToJSON,
    IncomesAfterMonthlyExpensesDataToJSONTyped,
} from './IncomesAfterMonthlyExpensesData';

/**
 * 
 * @export
 * @interface IncomeAfterFixedExpensesDto
 */
export interface IncomeAfterFixedExpensesDto {
    /**
     * 
     * @type {IncomesAfterMonthlyExpensesData}
     * @memberof IncomeAfterFixedExpensesDto
     */
    incomesAfterMonthlyExpenses?: IncomesAfterMonthlyExpensesData;
}

/**
 * Check if a given object implements the IncomeAfterFixedExpensesDto interface.
 */
export function instanceOfIncomeAfterFixedExpensesDto(value: object): value is IncomeAfterFixedExpensesDto {
    return true;
}

export function IncomeAfterFixedExpensesDtoFromJSON(json: any): IncomeAfterFixedExpensesDto {
    return IncomeAfterFixedExpensesDtoFromJSONTyped(json, false);
}

export function IncomeAfterFixedExpensesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeAfterFixedExpensesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'incomesAfterMonthlyExpenses': json['incomesAfterMonthlyExpenses'] == null ? undefined : IncomesAfterMonthlyExpensesDataFromJSON(json['incomesAfterMonthlyExpenses']),
    };
}

export function IncomeAfterFixedExpensesDtoToJSON(json: any): IncomeAfterFixedExpensesDto {
    return IncomeAfterFixedExpensesDtoToJSONTyped(json, false);
}

export function IncomeAfterFixedExpensesDtoToJSONTyped(value?: IncomeAfterFixedExpensesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incomesAfterMonthlyExpenses': IncomesAfterMonthlyExpensesDataToJSON(value['incomesAfterMonthlyExpenses']),
    };
}

