/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetSectionDto } from './BudgetSectionDto';
import {
    BudgetSectionDtoFromJSON,
    BudgetSectionDtoFromJSONTyped,
    BudgetSectionDtoToJSON,
    BudgetSectionDtoToJSONTyped,
} from './BudgetSectionDto';

/**
 * 
 * @export
 * @interface IncomesAfterMonthlyExpensesData
 */
export interface IncomesAfterMonthlyExpensesData {
    /**
     * 
     * @type {number}
     * @memberof IncomesAfterMonthlyExpensesData
     */
    total?: number;
    /**
     * 
     * @type {BudgetSectionDto}
     * @memberof IncomesAfterMonthlyExpensesData
     */
    monthlyIncomes?: BudgetSectionDto;
    /**
     * 
     * @type {BudgetSectionDto}
     * @memberof IncomesAfterMonthlyExpensesData
     */
    monthlyExpenses?: BudgetSectionDto;
    /**
     * 
     * @type {BudgetSectionDto}
     * @memberof IncomesAfterMonthlyExpensesData
     */
    savings?: BudgetSectionDto;
}

/**
 * Check if a given object implements the IncomesAfterMonthlyExpensesData interface.
 */
export function instanceOfIncomesAfterMonthlyExpensesData(value: object): value is IncomesAfterMonthlyExpensesData {
    return true;
}

export function IncomesAfterMonthlyExpensesDataFromJSON(json: any): IncomesAfterMonthlyExpensesData {
    return IncomesAfterMonthlyExpensesDataFromJSONTyped(json, false);
}

export function IncomesAfterMonthlyExpensesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomesAfterMonthlyExpensesData {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'monthlyIncomes': json['monthlyIncomes'] == null ? undefined : BudgetSectionDtoFromJSON(json['monthlyIncomes']),
        'monthlyExpenses': json['monthlyExpenses'] == null ? undefined : BudgetSectionDtoFromJSON(json['monthlyExpenses']),
        'savings': json['savings'] == null ? undefined : BudgetSectionDtoFromJSON(json['savings']),
    };
}

export function IncomesAfterMonthlyExpensesDataToJSON(json: any): IncomesAfterMonthlyExpensesData {
    return IncomesAfterMonthlyExpensesDataToJSONTyped(json, false);
}

export function IncomesAfterMonthlyExpensesDataToJSONTyped(value?: IncomesAfterMonthlyExpensesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'monthlyIncomes': BudgetSectionDtoToJSON(value['monthlyIncomes']),
        'monthlyExpenses': BudgetSectionDtoToJSON(value['monthlyExpenses']),
        'savings': BudgetSectionDtoToJSON(value['savings']),
    };
}

