/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyTransactionType } from './MonthlyTransactionType';
import {
    MonthlyTransactionTypeFromJSON,
    MonthlyTransactionTypeFromJSONTyped,
    MonthlyTransactionTypeToJSON,
    MonthlyTransactionTypeToJSONTyped,
} from './MonthlyTransactionType';

/**
 * 
 * @export
 * @interface MonthlyTransaction
 */
export interface MonthlyTransaction {
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    userId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MonthlyTransaction
     */
    amount?: number;
    /**
     * 
     * @type {MonthlyTransactionType}
     * @memberof MonthlyTransaction
     */
    monthlyTransactionType?: MonthlyTransactionType;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MonthlyTransaction
     */
    dayOfMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    accountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    subcategory?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MonthlyTransaction
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MonthlyTransaction
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MonthlyTransaction
     */
    type?: string | null;
}



/**
 * Check if a given object implements the MonthlyTransaction interface.
 */
export function instanceOfMonthlyTransaction(value: object): value is MonthlyTransaction {
    return true;
}

export function MonthlyTransactionFromJSON(json: any): MonthlyTransaction {
    return MonthlyTransactionFromJSONTyped(json, false);
}

export function MonthlyTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'monthlyTransactionType': json['monthlyTransactionType'] == null ? undefined : MonthlyTransactionTypeFromJSON(json['monthlyTransactionType']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MonthlyTransactionToJSON(json: any): MonthlyTransaction {
    return MonthlyTransactionToJSONTyped(json, false);
}

export function MonthlyTransactionToJSONTyped(value?: MonthlyTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'amount': value['amount'],
        'monthlyTransactionType': MonthlyTransactionTypeToJSON(value['monthlyTransactionType']),
        'notes': value['notes'],
        'dayOfMonth': value['dayOfMonth'],
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'subcategory': value['subcategory'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'type': value['type'],
    };
}

