/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlannedExpense
 */
export interface PlannedExpense {
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    itemType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpense
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PlannedExpense
     */
    isRecurring?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpense
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    categoryImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    categoryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpense
     */
    subCategory?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpense
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpense
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the PlannedExpense interface.
 */
export function instanceOfPlannedExpense(value: object): value is PlannedExpense {
    return true;
}

export function PlannedExpenseFromJSON(json: any): PlannedExpense {
    return PlannedExpenseFromJSONTyped(json, false);
}

export function PlannedExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedExpense {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'itemType': json['itemType'] == null ? undefined : json['itemType'],
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'isRecurring': json['isRecurring'] == null ? undefined : json['isRecurring'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryImage': json['categoryImage'] == null ? undefined : json['categoryImage'],
        'categoryColor': json['categoryColor'] == null ? undefined : json['categoryColor'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PlannedExpenseToJSON(json: any): PlannedExpense {
    return PlannedExpenseToJSONTyped(json, false);
}

export function PlannedExpenseToJSONTyped(value?: PlannedExpense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'itemType': value['itemType'],
        'name': value['name'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'isRecurring': value['isRecurring'],
        'totalAmount': value['totalAmount'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryImage': value['categoryImage'],
        'categoryColor': value['categoryColor'],
        'subCategory': value['subCategory'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

