/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlannedExpenseViewDto
 */
export interface PlannedExpenseViewDto {
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    itemType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpenseViewDto
     */
    date?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpenseViewDto
     */
    dayOfMonth?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlannedExpenseViewDto
     */
    isRecurring?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpenseViewDto
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    categoryImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    categoryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedExpenseViewDto
     */
    subCategory?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpenseViewDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlannedExpenseViewDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpenseViewDto
     */
    amountSpent?: number;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpenseViewDto
     */
    percentageSpent?: number;
    /**
     * 
     * @type {number}
     * @memberof PlannedExpenseViewDto
     */
    amountLeft?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlannedExpenseViewDto
     */
    readonly isCompleted?: boolean;
}

/**
 * Check if a given object implements the PlannedExpenseViewDto interface.
 */
export function instanceOfPlannedExpenseViewDto(value: object): value is PlannedExpenseViewDto {
    return true;
}

export function PlannedExpenseViewDtoFromJSON(json: any): PlannedExpenseViewDto {
    return PlannedExpenseViewDtoFromJSONTyped(json, false);
}

export function PlannedExpenseViewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedExpenseViewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'itemType': json['itemType'] == null ? undefined : json['itemType'],
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'isRecurring': json['isRecurring'] == null ? undefined : json['isRecurring'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryImage': json['categoryImage'] == null ? undefined : json['categoryImage'],
        'categoryColor': json['categoryColor'] == null ? undefined : json['categoryColor'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'amountSpent': json['amountSpent'] == null ? undefined : json['amountSpent'],
        'percentageSpent': json['percentageSpent'] == null ? undefined : json['percentageSpent'],
        'amountLeft': json['amountLeft'] == null ? undefined : json['amountLeft'],
        'isCompleted': json['isCompleted'] == null ? undefined : json['isCompleted'],
    };
}

export function PlannedExpenseViewDtoToJSON(json: any): PlannedExpenseViewDto {
    return PlannedExpenseViewDtoToJSONTyped(json, false);
}

export function PlannedExpenseViewDtoToJSONTyped(value?: Omit<PlannedExpenseViewDto, 'isCompleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'itemType': value['itemType'],
        'name': value['name'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'dayOfMonth': value['dayOfMonth'],
        'isRecurring': value['isRecurring'],
        'totalAmount': value['totalAmount'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryImage': value['categoryImage'],
        'categoryColor': value['categoryColor'],
        'subCategory': value['subCategory'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'amountSpent': value['amountSpent'],
        'percentageSpent': value['percentageSpent'],
        'amountLeft': value['amountLeft'],
    };
}

