/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Saving
 */
export interface Saving {
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    itemType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Saving
     */
    goalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Saving
     */
    savedAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Saving
     */
    amountPerMonth?: number;
    /**
     * 
     * @type {Date}
     * @memberof Saving
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Saving
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Saving interface.
 */
export function instanceOfSaving(value: object): value is Saving {
    return true;
}

export function SavingFromJSON(json: any): Saving {
    return SavingFromJSONTyped(json, false);
}

export function SavingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Saving {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'itemType': json['itemType'] == null ? undefined : json['itemType'],
        'name': json['name'] == null ? undefined : json['name'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
        'goalAmount': json['goalAmount'] == null ? undefined : json['goalAmount'],
        'savedAmount': json['savedAmount'] == null ? undefined : json['savedAmount'],
        'amountPerMonth': json['amountPerMonth'] == null ? undefined : json['amountPerMonth'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function SavingToJSON(json: any): Saving {
    return SavingToJSONTyped(json, false);
}

export function SavingToJSONTyped(value?: Saving | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'itemType': value['itemType'],
        'name': value['name'],
        'icon': value['icon'],
        'color': value['color'],
        'goalAmount': value['goalAmount'],
        'savedAmount': value['savedAmount'],
        'amountPerMonth': value['amountPerMonth'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

