/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * 
 * @export
 * @interface TransactionPagedResult
 */
export interface TransactionPagedResult {
    /**
     * 
     * @type {number}
     * @memberof TransactionPagedResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionPagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionPagedResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionPagedResult
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionPagedResult
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionPagedResult
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof TransactionPagedResult
     */
    data?: Array<Transaction> | null;
}

/**
 * Check if a given object implements the TransactionPagedResult interface.
 */
export function instanceOfTransactionPagedResult(value: object): value is TransactionPagedResult {
    return true;
}

export function TransactionPagedResultFromJSON(json: any): TransactionPagedResult {
    return TransactionPagedResultFromJSONTyped(json, false);
}

export function TransactionPagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPagedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function TransactionPagedResultToJSON(json: any): TransactionPagedResult {
    return TransactionPagedResultToJSONTyped(json, false);
}

export function TransactionPagedResultToJSONTyped(value?: TransactionPagedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TransactionToJSON)),
    };
}

