/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionType } from './TransactionType';
import {
    TransactionTypeFromJSON,
    TransactionTypeFromJSONTyped,
    TransactionTypeToJSON,
    TransactionTypeToJSONTyped,
} from './TransactionType';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    userId?: string | null;
    /**
     * 
     * @type {TransactionType}
     * @memberof Transaction
     */
    transactionType?: TransactionType;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    date?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    accountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    toAccountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    toAccountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    fromAccountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    fromAccountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    categoryImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    categoryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    subcategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    notes?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    isApplied?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    appliedAmount?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    isMonthly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    isRecurring?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    monthlyKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    recurringTimes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    recurringType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    savingKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    transferId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    removeFromSpendingPlan?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    yearMonth?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    day?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Transaction
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    type?: string | null;
}



/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'transactionType': json['transactionType'] == null ? undefined : TransactionTypeFromJSON(json['transactionType']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'toAccountId': json['toAccountId'] == null ? undefined : json['toAccountId'],
        'toAccountName': json['toAccountName'] == null ? undefined : json['toAccountName'],
        'fromAccountId': json['fromAccountId'] == null ? undefined : json['fromAccountId'],
        'fromAccountName': json['fromAccountName'] == null ? undefined : json['fromAccountName'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryImage': json['categoryImage'] == null ? undefined : json['categoryImage'],
        'categoryColor': json['categoryColor'] == null ? undefined : json['categoryColor'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'isApplied': json['isApplied'] == null ? undefined : json['isApplied'],
        'appliedAmount': json['appliedAmount'] == null ? undefined : json['appliedAmount'],
        'isMonthly': json['isMonthly'] == null ? undefined : json['isMonthly'],
        'isRecurring': json['isRecurring'] == null ? undefined : json['isRecurring'],
        'monthlyKey': json['monthlyKey'] == null ? undefined : json['monthlyKey'],
        'recurringTimes': json['recurringTimes'] == null ? undefined : json['recurringTimes'],
        'recurringType': json['recurringType'] == null ? undefined : json['recurringType'],
        'savingKey': json['savingKey'] == null ? undefined : json['savingKey'],
        'transferId': json['transferId'] == null ? undefined : json['transferId'],
        'removeFromSpendingPlan': json['removeFromSpendingPlan'] == null ? undefined : json['removeFromSpendingPlan'],
        'yearMonth': json['yearMonth'] == null ? undefined : json['yearMonth'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'day': json['day'] == null ? undefined : json['day'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TransactionToJSON(json: any): Transaction {
    return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'transactionType': TransactionTypeToJSON(value['transactionType']),
        'amount': value['amount'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'toAccountId': value['toAccountId'],
        'toAccountName': value['toAccountName'],
        'fromAccountId': value['fromAccountId'],
        'fromAccountName': value['fromAccountName'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryImage': value['categoryImage'],
        'categoryColor': value['categoryColor'],
        'subcategory': value['subcategory'],
        'notes': value['notes'],
        'isApplied': value['isApplied'],
        'appliedAmount': value['appliedAmount'],
        'isMonthly': value['isMonthly'],
        'isRecurring': value['isRecurring'],
        'monthlyKey': value['monthlyKey'],
        'recurringTimes': value['recurringTimes'],
        'recurringType': value['recurringType'],
        'savingKey': value['savingKey'],
        'transferId': value['transferId'],
        'removeFromSpendingPlan': value['removeFromSpendingPlan'],
        'yearMonth': value['yearMonth'],
        'year': value['year'],
        'month': value['month'],
        'day': value['day'],
        'metadata': value['metadata'],
        'type': value['type'],
    };
}

