/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * 
 * @export
 * @interface UpdateAccountCommand
 */
export interface UpdateAccountCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountCommand
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAccountCommand
     */
    currentBalance?: number;
    /**
     * 
     * @type {AccountType}
     * @memberof UpdateAccountCommand
     */
    accountType?: AccountType;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountCommand
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountCommand
     */
    image?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAccountCommand
     */
    isArchived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountCommand
     */
    accountId?: string | null;
}

/**
 * Check if a given object implements the UpdateAccountCommand interface.
 */
export function instanceOfUpdateAccountCommand(value: object): value is UpdateAccountCommand {
    return true;
}

export function UpdateAccountCommandFromJSON(json: any): UpdateAccountCommand {
    return UpdateAccountCommandFromJSONTyped(json, false);
}

export function UpdateAccountCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'currentBalance': json['currentBalance'] == null ? undefined : json['currentBalance'],
        'accountType': json['accountType'] == null ? undefined : AccountTypeFromJSON(json['accountType']),
        'color': json['color'] == null ? undefined : json['color'],
        'image': json['image'] == null ? undefined : json['image'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function UpdateAccountCommandToJSON(json: any): UpdateAccountCommand {
    return UpdateAccountCommandToJSONTyped(json, false);
}

export function UpdateAccountCommandToJSONTyped(value?: UpdateAccountCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'currentBalance': value['currentBalance'],
        'accountType': AccountTypeToJSON(value['accountType']),
        'color': value['color'],
        'image': value['image'],
        'isArchived': value['isArchived'],
        'accountId': value['accountId'],
    };
}

