/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlannedExpenseCommand
 */
export interface UpdatePlannedExpenseCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdatePlannedExpenseCommand
     */
    date?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdatePlannedExpenseCommand
     */
    dayOfMonth?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePlannedExpenseCommand
     */
    isRecurring?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdatePlannedExpenseCommand
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    categoryImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    categoryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    subCategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlannedExpenseCommand
     */
    plannedExpenseId?: string | null;
}

/**
 * Check if a given object implements the UpdatePlannedExpenseCommand interface.
 */
export function instanceOfUpdatePlannedExpenseCommand(value: object): value is UpdatePlannedExpenseCommand {
    return true;
}

export function UpdatePlannedExpenseCommandFromJSON(json: any): UpdatePlannedExpenseCommand {
    return UpdatePlannedExpenseCommandFromJSONTyped(json, false);
}

export function UpdatePlannedExpenseCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlannedExpenseCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'isRecurring': json['isRecurring'] == null ? undefined : json['isRecurring'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryImage': json['categoryImage'] == null ? undefined : json['categoryImage'],
        'categoryColor': json['categoryColor'] == null ? undefined : json['categoryColor'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
        'plannedExpenseId': json['plannedExpenseId'] == null ? undefined : json['plannedExpenseId'],
    };
}

export function UpdatePlannedExpenseCommandToJSON(json: any): UpdatePlannedExpenseCommand {
    return UpdatePlannedExpenseCommandToJSONTyped(json, false);
}

export function UpdatePlannedExpenseCommandToJSONTyped(value?: UpdatePlannedExpenseCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'dayOfMonth': value['dayOfMonth'],
        'isRecurring': value['isRecurring'],
        'totalAmount': value['totalAmount'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryImage': value['categoryImage'],
        'categoryColor': value['categoryColor'],
        'subCategory': value['subCategory'],
        'plannedExpenseId': value['plannedExpenseId'],
    };
}

