/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSavingCommand
 */
export interface UpdateSavingCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateSavingCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavingCommand
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavingCommand
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSavingCommand
     */
    goalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSavingCommand
     */
    savedAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSavingCommand
     */
    amountPerMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavingCommand
     */
    savingId?: string | null;
}

/**
 * Check if a given object implements the UpdateSavingCommand interface.
 */
export function instanceOfUpdateSavingCommand(value: object): value is UpdateSavingCommand {
    return true;
}

export function UpdateSavingCommandFromJSON(json: any): UpdateSavingCommand {
    return UpdateSavingCommandFromJSONTyped(json, false);
}

export function UpdateSavingCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSavingCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
        'goalAmount': json['goalAmount'] == null ? undefined : json['goalAmount'],
        'savedAmount': json['savedAmount'] == null ? undefined : json['savedAmount'],
        'amountPerMonth': json['amountPerMonth'] == null ? undefined : json['amountPerMonth'],
        'savingId': json['savingId'] == null ? undefined : json['savingId'],
    };
}

export function UpdateSavingCommandToJSON(json: any): UpdateSavingCommand {
    return UpdateSavingCommandToJSONTyped(json, false);
}

export function UpdateSavingCommandToJSONTyped(value?: UpdateSavingCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'icon': value['icon'],
        'color': value['color'],
        'goalAmount': value['goalAmount'],
        'savedAmount': value['savedAmount'],
        'amountPerMonth': value['amountPerMonth'],
        'savingId': value['savingId'],
    };
}

