/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyTransactionType } from './MonthlyTransactionType';
import {
    MonthlyTransactionTypeFromJSON,
    MonthlyTransactionTypeFromJSONTyped,
    MonthlyTransactionTypeToJSON,
    MonthlyTransactionTypeToJSONTyped,
} from './MonthlyTransactionType';

/**
 * 
 * @export
 * @interface UpdateMonthlyTransactionCommand
 */
export interface UpdateMonthlyTransactionCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateMonthlyTransactionCommand
     */
    amount?: number;
    /**
     * 
     * @type {MonthlyTransactionType}
     * @memberof UpdateMonthlyTransactionCommand
     */
    monthlyTransactionType?: MonthlyTransactionType;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateMonthlyTransactionCommand
     */
    dayOfMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    accountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    subcategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMonthlyTransactionCommand
     */
    id?: string | null;
}



/**
 * Check if a given object implements the UpdateMonthlyTransactionCommand interface.
 */
export function instanceOfUpdateMonthlyTransactionCommand(value: object): value is UpdateMonthlyTransactionCommand {
    return true;
}

export function UpdateMonthlyTransactionCommandFromJSON(json: any): UpdateMonthlyTransactionCommand {
    return UpdateMonthlyTransactionCommandFromJSONTyped(json, false);
}

export function UpdateMonthlyTransactionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMonthlyTransactionCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'monthlyTransactionType': json['monthlyTransactionType'] == null ? undefined : MonthlyTransactionTypeFromJSON(json['monthlyTransactionType']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UpdateMonthlyTransactionCommandToJSON(json: any): UpdateMonthlyTransactionCommand {
    return UpdateMonthlyTransactionCommandToJSONTyped(json, false);
}

export function UpdateMonthlyTransactionCommandToJSONTyped(value?: UpdateMonthlyTransactionCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'monthlyTransactionType': MonthlyTransactionTypeToJSON(value['monthlyTransactionType']),
        'notes': value['notes'],
        'dayOfMonth': value['dayOfMonth'],
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'subcategory': value['subcategory'],
        'id': value['id'],
    };
}

