/* tslint:disable */
/* eslint-disable */
/**
 * Budget Manager API
 * Personal finance management API for tracking income, expenses, accounts, and budgets.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryType } from './CategoryType';
import {
    CategoryTypeFromJSON,
    CategoryTypeFromJSONTyped,
    CategoryTypeToJSON,
    CategoryTypeToJSONTyped,
} from './CategoryType';

/**
 * 
 * @export
 * @interface UpdateCategoryCommand
 */
export interface UpdateCategoryCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryCommand
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryCommand
     */
    color?: string | null;
    /**
     * 
     * @type {CategoryType}
     * @memberof UpdateCategoryCommand
     */
    categoryType?: CategoryType;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCategoryCommand
     */
    subcategories?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryCommand
     */
    categoryId?: string | null;
}



/**
 * Check if a given object implements the UpdateCategoryCommand interface.
 */
export function instanceOfUpdateCategoryCommand(value: object): value is UpdateCategoryCommand {
    return true;
}

export function UpdateCategoryCommandFromJSON(json: any): UpdateCategoryCommand {
    return UpdateCategoryCommandFromJSONTyped(json, false);
}

export function UpdateCategoryCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoryCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'color': json['color'] == null ? undefined : json['color'],
        'categoryType': json['categoryType'] == null ? undefined : CategoryTypeFromJSON(json['categoryType']),
        'subcategories': json['subcategories'] == null ? undefined : json['subcategories'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}

export function UpdateCategoryCommandToJSON(json: any): UpdateCategoryCommand {
    return UpdateCategoryCommandToJSONTyped(json, false);
}

export function UpdateCategoryCommandToJSONTyped(value?: UpdateCategoryCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'color': value['color'],
        'categoryType': CategoryTypeToJSON(value['categoryType']),
        'subcategories': value['subcategories'],
        'categoryId': value['categoryId'],
    };
}

